#!/usr/bin/env bash
# Bash script that redirects to another page.

# Updates Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creates an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performs a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/faith2221 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
sudo service nginx restart

