#!/usr/bin/env bash
# Bash script that redirects to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/root/index.html
string_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.example.com permanent;"
sudo sed -i "s/server_name -;/$string_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
