#!/usr/bin/env bash
# Script configures Nginx server so to redirect-me to another page.

# Updating packages before installation
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Performing  a "moved permanently redirection (301"
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/faith2221 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Performs  a " moved permanent redirection (301)"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/
404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Tests configuration for syntax errors
sudo nginx -t

# Restarts nginx after implemented changes
sudo service nginx restart
