#!/usr/bin/env bash
# Script thats displays to infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# Displays "I am invicible!!!" when receiving SIGTERM signal

trap "'echo"I am invicible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
