#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd
# Script displays username, user id, Home directory path for the user
# Requirement is use the while loop (for and until are forbidden)

while read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
