#!/usr/bin/env bash
# Script that displays the visitor IP along with the HTTP
status code from the Apache log file
# Must use awk and not allowed to use while, for, until and cut
awk '{print $1 " " $9}' apache-access.log
