#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code,
and displays this data
# Reqired that format must be OCCURENCE_NUMBER IP HTTP_CODE
# In list format, ordered from the greatest to the lowest number of occurrences
# Must use awk, not allowed to use while, for, until and cut
awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
